# https://taskfile.dev/
version: '3'


tasks:
  i:
    desc: "depencies installing"
    cmds:
      - poetry install
    sources:
      - pyproject.toml
    generates:
      - poetry.lock

  b:
    desc: "build the project"
    cmds:
      - poetry build
  
  r:
    desc: "run brain-games"
    cmds:
      - poetry run brain-games

  publish:
    cmds:
      - poetry publish --dry-run

  package-install:
    cmds:
      - pip install --user dist/*.whl
  
  f:
    desc: invoke flake8
    cmds:
      - poetry run flake8 brain_games
