# https://taskfile.dev/
version: '3'


tasks:
  i:
    desc: "depencies installing"
    cmds:
      - poetry install
    sources:
      - pyproject.toml
    generates:
      - poetry.lock

  b:
    desc: "build the project"
    cmds:
      - poetry build
  
  r:
    desc: "run brain-games"
    cmds:
      - poetry run brain-games
  
  dist:
    cmds:
      - python -m pip install --user dist/*.whl
